version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: postgres
      POSTGRES_DB: telegram
    ports:
      - 5432:5432 